// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFileInfoByPid(arg1:number):Promise<main.FileInfo>;

export function InjectExe(arg1:string):Promise<void>;

export function OpenExeDialog():Promise<string>;

export function OpenFileByDefaultApplication(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function StartListenUDP():Promise<void>;
