// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileInfoByPid(arg1) {
  return window['go']['main']['App']['GetFileInfoByPid'](arg1);
}

export function InjectExe(arg1) {
  return window['go']['main']['App']['InjectExe'](arg1);
}

export function OpenExeDialog() {
  return window['go']['main']['App']['OpenExeDialog']();
}

export function OpenFileByDefaultApplication(arg1) {
  return window['go']['main']['App']['OpenFileByDefaultApplication'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function StartListenUDP() {
  return window['go']['main']['App']['StartListenUDP']();
}
