name: Build CI Version

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build HookLib
        working-directory: HookLib
        run: |
          mkdir build
          cd build
          cmake -DCI_BUILD="true" -DCMAKE_GENERATOR_PLATFORM=Win32 -G "Visual Studio 17 2022" ..
          cmake --build . --config Release

      - name: Setup go1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build GUI
        working-directory: frontend
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          cd frontend
          npm install
          npm run build
          cd ../
          choco install upx
          wails build -clean -upx -webview2 error

      - name: Copy File To Release
        run: |
          mkdir release
          copy HookLib/build/Release/HookDemo.dll release
          copy HookLib/build/Release/Injector.exe release
          copy frontend/build/bin/SwordArtOffline.exe release
          copy frontend/LuaEngine.lua release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SwordArtOffline
          path: release
          if-no-files-found: error
          retention-days: 30
